apiVersion: v1
kind: Pod
metadata:
  name: defrag-debug
  labels:
    name: defrag-debug
spec:
  containers:
  - name: defrag-debug
    image: hkube/etcd-defrag-cron:v1.0.0
    command: ["sh", "-c", "sleep 3600" ]    
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    
